In [5]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(1, len(X)):
        y_hat = prediction(X[i], W, b)
        error = y[i]-y_hat
        if error == 1:
            W[0]+=learn_rate*X[i][0]
            W[1]+=learn_rate*X[i][1]
            b += learn_rate

        elif error == -1:
            W[0]-=learn_rate*X[i][0]
            W[1]-=learn_rate*X[i][1]
            b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [9]:
from pandas import read_csv
# this function returns a DataFrame
data = read_csv("data.csv", header=None).values
X = data[:, 0:2]
y = data[:, 2]

trainPerceptronAlgorithm(X, y, num_epochs=25)

[(array([1.10978832]), array([4.46888546])),
 (array([0.03241705]), array([1.42964659])),
 (array([-0.22131743]), array([0.73284983])),
 (array([-0.24498341]), array([0.6751207])),
 (array([-0.26118871]), array([0.64953538])),
 (array([-0.27362548]), array([0.63916146])),
 (array([-0.28305131]), array([0.64400617])),
 (array([-0.29262113]), array([0.64892489])),
 (array([-0.30233825]), array([0.65391933])),
 (array([-0.31220611]), array([0.65899123])),
 (array([-0.32222824]), array([0.66414244])),
 (array([-0.33162844]), array([0.66899033])),
 (array([-0.34116687]), array([0.67390951])),
 (array([-0.35084663]), array([0.67890157])),
 (array([-0.36067086]), array([0.68396815])),
 (array([-0.37409998]), array([0.67289192])),
 (array([-0.3817292]), array([0.67733739])),
 (array([-0.3894599]), array([0.68184198])),
 (array([-0.39729412]), array([0.6864069])),
 (array([-0.40523394]), array([0.69103334])),
 (array([-0.41328152]), array([0.69572258])),
 (array([-0.42143906]), array([0.7004758